# Generated by Django 4.2.1 on 2023-06-30 14:45

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_unique_lowered"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_lowered",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("username"),
                name="unique_lowered_username",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="unique_lowered_email",
            ),
        ),
    ]
