version: '3.8'

services:
  db:
    image: postgres:14.0-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    container_name: user_balance_db
  
  backend:
    build: ./User_balance
    restart: always
    ports:
      - 8000:8000
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
    container_name: user_balance_backend

volumes:
  db_data:
  static_value:
  media_value: