version: '3.8'

services:
  db:
    image: postgres:14.0-alpine
    restart: always
    environment:
          - ENGINE=django.db.backends.postgresql_psycopg2
          - NAME=postgres
          - USER=postgres
          - PASSWORD=postgres
          - HOST="db"
          - PORT=5432
          - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    container_name: user_balance_db
  
  backend:
    build: .
    restart: always
    volumes:
      - static_value:/app/cdn/static/
      - media_value:/app/cdn/media/
    depends_on:
      - db
    container_name: user_balance_backend

  nginx:
      image: nginx:1.21-alpine
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
        - static_value:/var/html/static/
        - media_value:/var/html/media/
      depends_on:
        - backend
      container_name: nginx


volumes:
  db_data:
  static_value:
  media_value: