version: '3.8'

services:
  db:
    image: postgres:14.0-alpine
    restart: always
    environment:
          - ENGINE=django.db.backends.postgresql_psycopg2
          - NAME=postgres
          - USER=postgres
          - PASSWORD=postgres
          - HOST="db"
          - PORT=5432
          - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    container_name: user_balance_db
  
  backend:
    build: .
    restart: always
    ports:
      - 8000:8000
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    container_name: user_balance_backend

volumes:
  db_data:
  static_value:
  media_value: