[tool.black]
line-length = 79
exclude = ".*/migrations/.*.py"

[tool.isort]
line_length = 79
known_first_party = "apps"
profile = "black"
skip_glob = ["**/migrations/**.py"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "User_balance.settings"
python_files = ["test_*.py"]
addopts = "--reuse-db"
