# Generated by Django 4.2.1 on 2023-07-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type_oper",
            field=models.CharField(
                choices=[("DP", "deposit"), ("TR", "transfer")],
                default="DP",
                max_length=20,
            ),
        ),
    ]
