# Generated by Django 4.2.1 on 2023-06-30 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_delete_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transfer",
            options={
                "verbose_name": "трансфер",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
