# Generated by Django 4.2.1 on 2023-07-01 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0003_alter_transfer_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "type_oper",
                    models.CharField(
                        choices=[
                            ("deposit", "DEPOSIT"),
                            ("transfer", "TRANSFER"),
                        ],
                        default="deposit",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_from",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="from_user",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="to_user",
        ),
        migrations.DeleteModel(
            name="Action",
        ),
        migrations.DeleteModel(
            name="Transfer",
        ),
    ]
