# Generated by Django 4.2.1 on 2023-07-01 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0004_transaction_remove_transfer_from_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="participant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
