# Generated by Django 4.2.1 on 2023-07-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_transaction_participant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.IntegerField(),
        ),
    ]
